In [3]:
import torch

In [11]:
a = torch.tensor([[1,0,0], 
                  [1,1,1]])
b = torch.tensor([[1,1,1], 
                  [0,0,0]])
a*b

tensor([[1, 0, 0],
        [0, 0, 0]])

In [13]:
(a*b).shape

torch.Size([2, 3])

In [40]:
c = torch.randint(0,9,[2,2,3])
c, c.flatten(2)

(tensor([[[6, 0, 3],
          [2, 1, 1]],
 
         [[7, 1, 1],
          [7, 3, 0]]]),
 tensor([[[6, 0, 3],
          [2, 1, 1]],
 
         [[7, 1, 1],
          [7, 3, 0]]]))

In [42]:
c

tensor([[[6, 0, 3],
         [2, 1, 1]],

        [[7, 1, 1],
         [7, 3, 0]]])

In [ ]:
torch.sum(c, -1), torch.sum(c, -1).shape

(tensor([[ 9,  4],
         [ 9, 10]]),
 torch.Size([2, 2]))

In [12]:
torch.sum(a*b, -1)

tensor([1, 0])

In [57]:
yellow_pred = torch.tensor([
    [0,1,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,1,1,1]
])
yellow_true = torch.tensor([
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,1,0],
    [0,0,1,1,1]
])

green_pred = torch.tensor([
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0],
    [1,1,0,0,0],
    [1,1,0,0,0]
])
green_true = torch.tensor([
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0],
    [1,0,0,0,0],
    [1,1,0,0,0]
])

pred = torch.stack([yellow_pred, green_pred])
true = torch.stack([yellow_true, green_true])

torch.sum(pred.flatten(2) * true.flatten(2), -1)

tensor([[0, 0, 0, 0, 3],
        [0, 0, 0, 1, 2]])